### ISSUE TITLE
Setup deployment for the 2022 edition

### ISSUE THREAD

**Issue by AdamSiekierski** [tripleadev/zsk-amnesty#41]
I'd suggest using [fly.io](https://fly.io/) for that... that way, we'll be able to omit having to use Prisma Cloud, and have the whole deployment in one place... also, we don't quite need to have the app deployed on the edge, and a simpler solution is just putting it as a monolith.

**Comment by datejer** [comment]
With that, we would need to give up the `stale-while-revalidate` CDN caching strategy provided by the Vercel edge. Do we have any way of dealing with this as a standalone deployment?

**Comment by AdamSiekierski** [comment]
well, we might actually not _need_ `stale-while-revalidate`... I'm thinking currently of two solutions - first, that would still allow us to use it, would be taking advantage of a Cache/CDN like CloudFlare (Fly.io doesn't provide any cache whatsoever)... second would be caching the stats endpoint from inside the code... when the app is `serverful` we can totally just hold it in a variable... or put a Redis instance next to the app and hold it there...
As for now, we can totally just deploy it the "basic" way, and then when we have a strategy (related to #42) we can maybe do some more actions here

**Comment by datejer** [comment]
Update: fly.io sucks.
